
server.port=${PORT:8080}


spring.application.name=bfhl


debug=false


app.user.full-name=anmol_prajapati
app.user.dob=04032006
app.user.email=anmolprajapati802@gmail.com
app.user.roll-number=2310991525